branches:
  only:
    - appveyor

environment:

  matrix:

    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install six"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install ."


