environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"


install:
  - "%PYTHON%/Scripts/pip.exe install six lxml==3.6"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install ."

build_script:
  # Build the compiled extension
- "%CMD_IN_ENV% python setup.py build"


test_script:
  - mkdir example_files\metabolights
  - ps: Invoke-WebRequest  "ftp.ebi.ac.uk/pub/databases/metabolights/studies/public" -OutFile "example_files\metabolights"
  - wget https://github.com/ISA-tools/ISAvalidator-ISAconverter-BIImanager/releases/download/1.6.5/ISA-validator-1.6.5.zip
  - unzip ISA-validator-1.6.5.zip
  - wget ftp://ftp.ebi.ac.uk/pub/databases/metabolights/submissionTool/ISAcreatorMetaboLights.zip
  - unzip ISAcreatorMetaboLights.zip
  - mzml2isa -i example_files\metabolights\MTBLS267 -o out_folder\metabolights -s MTBLS267
  - java -cp ISA-validator-1.6.5\isatools_deps.jar org.isatools.isatab.manager.SimpleManager validate out_folder\metabolights\MTBLS267 Configurations\MetaboLightsConfig20140506\

after_test:
  # If tests are successful, create binary packages for the project.
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python setup.py bdist_wininst"
  - "%CMD_IN_ENV% python setup.py bdist_msi"
  - ps: "ls dist"

